baseURL = 'https://zhuolovesmath57.github.io/my_website/'
languageCode = 'en-us'
title = "Zhuo's Website"

theme = "hugo_paper"

[[params.socialIcons]]
name = "email"
url = "mailto:zhuoz4@illinois.edu"